# Generated by Django 6.1 on 2026-08-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(default='fa-box', help_text='Clase Font Awesome, ej: fa-tree', max_length=80, verbose_name='Ícono FA')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('imagen_url', models.URLField(blank=True, help_text='URL de imagen externa (Unsplash, etc.) si no se sube archivo', verbose_name='URL de imagen externa')),
                ('precio', models.DecimalField(blank=True, decimal_places=0, help_text='Precio referencial en CLP (opcional)', max_digits=12, null=True, verbose_name='Precio (CLP)')),
                ('especies', models.CharField(blank=True, help_text='Ej: Pino Oregón, Acacia', max_length=250, verbose_name='Especies de madera')),
                ('espesores', models.CharField(blank=True, help_text='Ej: 18mm, 25mm, 32mm', max_length=200, verbose_name='Espesores disponibles')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
